### ISSUE TITLE
Serializable FeatureState / NamedFeature

### ISSUE THREAD

**Issue by tdtappe** [togglz/togglz#129]
I wanted to provide a ("clustered") feature cache by implementing a StateRepository. But unfortunately the FeatureState is actually not Serializable. Well, the FeatureState itself might be Serializable but not with a NamedFeature inside.

**Comment by chkal** [comment]
Ah, I see. Yeah, I agree. This should be easy to fix. Pull requests welcome. ;)

**Comment by tdtappe** [comment]
I gave it a try. But I couldn't even build togglz because of some plugin error. Any idea?

[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Togglz
[INFO] Togglz - Core Framework
[INFO] Togglz - Test Harness
[INFO] Togglz - SLF4J integration
[INFO] Togglz - Servlet integration
[INFO] Togglz - Admin Console
[INFO] Togglz - CDI integration
[INFO] Togglz - Guice integration
[INFO] Togglz - Spring Framework integration
[INFO] Togglz - Spring Web integration
[INFO] Togglz - Spring Security integration
[INFO] Togglz - DeltaSpike integration
[INFO] Togglz - Apache Shiro integration
[INFO] Togglz - JSF integration
[INFO] Togglz - JSP integration
[INFO] Togglz - Google App Engine Integration
[INFO] Togglz - Netflix Archaius Integration
[INFO] Togglz - MongoDB integration
[INFO] Togglz - Seam Security integration
[INFO] Togglz - Testing Support
[INFO] Togglz - JUnit integration
[INFO] Togglz - Distribution
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Togglz 2.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ togglz-project ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ togglz-project ---
[INFO] 
[INFO] --- org.eclipse.virgo.bundlor.maven:1.1.2.RELEASE:bundlor (bundlor) @ togglz-project ---
[WARNING] Error injecting: org.eclipse.virgo.bundlor.maven.plugin.BundlorMojo
java.lang.NoClassDefFoundError: org/eclipse/virgo/bundlor/support/manifestwriter/ManifestWriterFactory
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2585)
	at java.lang.Class.getDeclaredConstructors(Class.java:1906)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:99)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:657)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:875)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:798)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:281)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:213)
	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:998)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1031)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:994)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1044)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:113)
	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:122)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:82)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:464)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:119)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: org.eclipse.virgo.bundlor.support.manifestwriter.ManifestWriterFactory
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 54 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Togglz ............................................. FAILURE [  0.787 s]
[INFO] Togglz - Core Framework ............................ SKIPPED
[INFO] Togglz - Test Harness .............................. SKIPPED
[INFO] Togglz - SLF4J integration ......................... SKIPPED
[INFO] Togglz - Servlet integration ....................... SKIPPED
[INFO] Togglz - Admin Console ............................. SKIPPED
[INFO] Togglz - CDI integration ........................... SKIPPED
[INFO] Togglz - Guice integration ......................... SKIPPED
[INFO] Togglz - Spring Framework integration .............. SKIPPED
[INFO] Togglz - Spring Web integration .................... SKIPPED
[INFO] Togglz - Spring Security integration ............... SKIPPED
[INFO] Togglz - DeltaSpike integration .................... SKIPPED
[INFO] Togglz - Apache Shiro integration .................. SKIPPED
[INFO] Togglz - JSF integration ........................... SKIPPED
[INFO] Togglz - JSP integration ........................... SKIPPED
[INFO] Togglz - Google App Engine Integration ............. SKIPPED
[INFO] Togglz - Netflix Archaius Integration .............. SKIPPED
[INFO] Togglz - MongoDB integration ....................... SKIPPED
[INFO] Togglz - Seam Security integration ................. SKIPPED
[INFO] Togglz - Testing Support ........................... SKIPPED
[INFO] Togglz - JUnit integration ......................... SKIPPED
[INFO] Togglz - Distribution .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.041 s
[INFO] Finished at: 2015-05-08T09:51:22+02:00
[INFO] Final Memory: 20M/438M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.virgo.bundlor:org.eclipse.virgo.bundlor.maven:1.1.2.RELEASE:bundlor (bundlor) on project togglz-project: Execution bundlor of goal org.eclipse.virgo.bundlor:org.eclipse.virgo.bundlor.maven:1.1.2.RELEASE:bundlor failed: A required class was missing while executing org.eclipse.virgo.bundlor:org.eclipse.virgo.bundlor.maven:1.1.2.RELEASE:bundlor: org/eclipse/virgo/bundlor/support/manifestwriter/ManifestWriterFactory
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.eclipse.virgo.bundlor:org.eclipse.virgo.bundlor.maven:1.1.2.RELEASE
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/Tappe/.m2/repository/org/eclipse/virgo/bundlor/org.eclipse.virgo.bundlor.maven/1.1.2.RELEASE/org.eclipse.virgo.bundlor.maven-1.1.2.RELEASE.jar
[ERROR] urls[1] = file:/C:/Users/Tappe/.m2/repository/org/eclipse/virgo/util/org.eclipse.virgo.util.osgi/3.5.0.RELEASE/org.eclipse.virgo.util.osgi-3.5.0.RELEASE.jar
[ERROR] urls[2] = file:/C:/Users/Tappe/.m2/repository/org/eclipse/virgo/util/org.eclipse.virgo.util.common/3.5.0.RELEASE/org.eclipse.virgo.util.common-3.5.0.RELEASE.jar
[ERROR] urls[3] = file:/C:/Users/Tappe/.m2/repository/org/eclipse/virgo/util/org.eclipse.virgo.util.parser.manifest/3.5.0.RELEASE/org.eclipse.virgo.util.parser.manifest-3.5.0.RELEASE.jar
[ERROR] urls[4] = file:/C:/Users/Tappe/.m2/repository/org/apache/maven/com.springsource.org.apache.maven.plugin-api/3.0.4/com.springsource.org.apache.maven.plugin-api-3.0.4.jar
[ERROR] urls[5] = file:/C:/Users/Tappe/.m2/repository/org/apache/ant/com.springsource.org.apache.tools.ant/1.7.0/com.springsource.org.apache.tools.ant-1.7.0.jar
[ERROR] urls[6] = file:/C:/Users/Tappe/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.eclipse.virgo.bundlor.support.manifestwriter.ManifestWriterFactory
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.virgo.bundlor:org.eclipse.virgo.bundlor.maven:1.1.2.RELEASE:bundlor (bundlor) on project togglz-project: Execution bundlor of goal org.eclipse.virgo.bundlor:org.eclipse.virgo.bundlor.maven:1.1.2.RELEASE:bundlor failed: A required class was missing while executing org.eclipse.virgo.bundlor:org.eclipse.virgo.bundlor.maven:1.1.2.RELEASE:bundlor: org/eclipse/virgo/bundlor/support/manifestwriter/ManifestWriterFactory
-----------------------------------------------------
realm =    plugin>org.eclipse.virgo.bundlor:org.eclipse.virgo.bundlor.maven:1.1.2.RELEASE
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/C:/Users/Tappe/.m2/repository/org/eclipse/virgo/bundlor/org.eclipse.virgo.bundlor.maven/1.1.2.RELEASE/org.eclipse.virgo.bundlor.maven-1.1.2.RELEASE.jar
urls[1] = file:/C:/Users/Tappe/.m2/repository/org/eclipse/virgo/util/org.eclipse.virgo.util.osgi/3.5.0.RELEASE/org.eclipse.virgo.util.osgi-3.5.0.RELEASE.jar
urls[2] = file:/C:/Users/Tappe/.m2/repository/org/eclipse/virgo/util/org.eclipse.virgo.util.common/3.5.0.RELEASE/org.eclipse.virgo.util.common-3.5.0.RELEASE.jar
urls[3] = file:/C:/Users/Tappe/.m2/repository/org/eclipse/virgo/util/org.eclipse.virgo.util.parser.manifest/3.5.0.RELEASE/org.eclipse.virgo.util.parser.manifest-3.5.0.RELEASE.jar
urls[4] = file:/C:/Users/Tappe/.m2/repository/org/apache/maven/com.springsource.org.apache.maven.plugin-api/3.0.4/com.springsource.org.apache.maven.plugin-api-3.0.4.jar
urls[5] = file:/C:/Users/Tappe/.m2/repository/org/apache/ant/com.springsource.org.apache.tools.ant/1.7.0/com.springsource.org.apache.tools.ant-1.7.0.jar
urls[6] = file:/C:/Users/Tappe/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution bundlor of goal org.eclipse.virgo.bundlor:org.eclipse.virgo.bundlor.maven:1.1.2.RELEASE:bundlor failed: A required class was missing while executing org.eclipse.virgo.bundlor:org.eclipse.virgo.bundlor.maven:1.1.2.RELEASE:bundlor: org/eclipse/virgo/bundlor/support/manifestwriter/ManifestWriterFactory
-----------------------------------------------------
realm =    plugin>org.eclipse.virgo.bundlor:org.eclipse.virgo.bundlor.maven:1.1.2.RELEASE
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/C:/Users/Tappe/.m2/repository/org/eclipse/virgo/bundlor/org.eclipse.virgo.bundlor.maven/1.1.2.RELEASE/org.eclipse.virgo.bundlor.maven-1.1.2.RELEASE.jar
urls[1] = file:/C:/Users/Tappe/.m2/repository/org/eclipse/virgo/util/org.eclipse.virgo.util.osgi/3.5.0.RELEASE/org.eclipse.virgo.util.osgi-3.5.0.RELEASE.jar
urls[2] = file:/C:/Users/Tappe/.m2/repository/org/eclipse/virgo/util/org.eclipse.virgo.util.common/3.5.0.RELEASE/org.eclipse.virgo.util.common-3.5.0.RELEASE.jar
urls[3] = file:/C:/Users/Tappe/.m2/repository/org/eclipse/virgo/util/org.eclipse.virgo.util.parser.manifest/3.5.0.RELEASE/org.eclipse.virgo.util.parser.manifest-3.5.0.RELEASE.jar
urls[4] = file:/C:/Users/Tappe/.m2/repository/org/apache/maven/com.springsource.org.apache.maven.plugin-api/3.0.4/com.springsource.org.apache.maven.plugin-api-3.0.4.jar
urls[5] = file:/C:/Users/Tappe/.m2/repository/org/apache/ant/com.springsource.org.apache.tools.ant/1.7.0/com.springsource.org.apache.tools.ant-1.7.0.jar
urls[6] = file:/C:/Users/Tappe/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:166)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: org.apache.maven.plugin.PluginContainerException: A required class was missing while executing org.eclipse.virgo.bundlor:org.eclipse.virgo.bundlor.maven:1.1.2.RELEASE:bundlor: org/eclipse/virgo/bundlor/support/manifestwriter/ManifestWriterFactory
-----------------------------------------------------
realm =    plugin>org.eclipse.virgo.bundlor:org.eclipse.virgo.bundlor.maven:1.1.2.RELEASE
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/C:/Users/Tappe/.m2/repository/org/eclipse/virgo/bundlor/org.eclipse.virgo.bundlor.maven/1.1.2.RELEASE/org.eclipse.virgo.bundlor.maven-1.1.2.RELEASE.jar
urls[1] = file:/C:/Users/Tappe/.m2/repository/org/eclipse/virgo/util/org.eclipse.virgo.util.osgi/3.5.0.RELEASE/org.eclipse.virgo.util.osgi-3.5.0.RELEASE.jar
urls[2] = file:/C:/Users/Tappe/.m2/repository/org/eclipse/virgo/util/org.eclipse.virgo.util.common/3.5.0.RELEASE/org.eclipse.virgo.util.common-3.5.0.RELEASE.jar
urls[3] = file:/C:/Users/Tappe/.m2/repository/org/eclipse/virgo/util/org.eclipse.virgo.util.parser.manifest/3.5.0.RELEASE/org.eclipse.virgo.util.parser.manifest-3.5.0.RELEASE.jar
urls[4] = file:/C:/Users/Tappe/.m2/repository/org/apache/maven/com.springsource.org.apache.maven.plugin-api/3.0.4/com.springsource.org.apache.maven.plugin-api-3.0.4.jar
urls[5] = file:/C:/Users/Tappe/.m2/repository/org/apache/ant/com.springsource.org.apache.tools.ant/1.7.0/com.springsource.org.apache.tools.ant-1.7.0.jar
urls[6] = file:/C:/Users/Tappe/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:164)
	... 20 more
Caused by: java.lang.NoClassDefFoundError: org/eclipse/virgo/bundlor/support/manifestwriter/ManifestWriterFactory
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2585)
	at java.lang.Class.getDeclaredConstructors(Class.java:1906)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:99)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:657)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:875)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:798)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:281)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:213)
	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:998)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1031)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:994)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1044)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:113)
	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:122)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:82)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:464)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:119)
	... 20 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.virgo.bundlor.support.manifestwriter.ManifestWriterFactory
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 54 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by chkal** [comment]
Hmmm. Weird. All you need ist Java 7 and a recent version of Maven. Maven 3.1.x or newer should work fine.

**Comment by tdtappe** [comment]
Seems to work after adding the following dependencies to the org.eclipse.virgo.bundlor.maven plugin.

			<dependency>
				<groupId>org.eclipse.virgo.bundlor</groupId>
				<artifactId>org.eclipse.virgo.bundlor</artifactId>
				<version>1.1.2.RELEASE</version>
			</dependency>
			<dependency>
				<groupId>org.eclipse.virgo.bundlor</groupId>
				<artifactId>org.eclipse.virgo.bundlor.blint</artifactId>
				<version>1.1.2.RELEASE</version>
			</dependency>

**Comment by tdtappe** [comment]
BTW, I use maven version 3.2.5

**Comment by tdtappe** [comment]
I hopefully managed to create a pull request. This was the first time I used Git / GitHub :-)

**Comment by tdtappe** [comment]
Oh. The tests didn't work. I thought it would be Ok to use Java 7 because you mentioned it above. Should be fixed now.

**Comment by RichSteele** [comment]
Not sure I'm too late to the party and haven't had a chance to look at the
pull request yet but I've been able to build on Windows using Java 7, Maven
3.2.5, and a -DJBOSS_REPO=true passed on the command line; e.g.,

mvn  -DJBOSS_REPO=true clean package

I do remember seeing errors like these in my early days of trying to build,
but I didn't need to update any dependencies to make things work.

**Comment by chkal** [comment]
@RichSteele: I think the CI server also builds Togglz with JDK6 currently. So if the source code uses JDK7 stuff, the build fails. However, I was thinking about dropping JDK6 support. Even JDK7 is EOL now. ;)

@tdtappe: Thanks a lot for the pull request. However, it look like you reformatted the full source code. So it is nearly impossible to see what you changed. 

See: 
https://github.com/tdtappe/togglz/commit/fd9b0fb6bd09876105928c30f3651af6402f001b

Could you perhaps recreate the pull request without modifying the source code format? That would be great. There is also an Eclipse code format profile named `eclipse-code-format.xml` in the source repository. Thanks a lot.

**Comment by tdtappe** [comment]
Sure. No problem. Done!
I didn't notice the differences in whitespace as I switched it off in my diff viewer. Sorry for that.

BTW, did you notice the usage of tabs AND spaces for identation in NamedFeature?

**Comment by chkal** [comment]
Thanks a lot. I just fixed the source formatting.

**Comment by chkal** [comment]
Closing because FeatureState and NamedFeature are Serializable now.
