### ISSUE TITLE
ConsoleServlet not usable with TestFeatureManager (NPE)

### ISSUE THREAD

**Issue by BastianVoigt** [togglz/togglz#142]
When using the TestFeatureManager, the Console Servlet throws a NullPointerException, because the TestFeatureManager returns null from getActivationStrategies()

    java.lang.NullPointerException
    	at java.util.ArrayList.<init>(ArrayList.java:177)
    	at org.togglz.console.model.FeatureModel.<init>(FeatureModel.java:44)
    	at org.togglz.console.handlers.index.IndexPageTabView.add(IndexPageTabView.java:37)
    	at org.togglz.console.handlers.index.IndexPageHandler.process(IndexPageHandler.java:42)
    	at org.togglz.console.TogglzConsoleServlet.service(TogglzConsoleServlet.java:56)
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)

**Comment by chkal** [comment]
Fixed by #143
