### ISSUE TITLE
ZookeeperStateRepositoryTest::testZkNodeChangesUpdateFeatureState is flaky

### ISSUE THREAD

**Issue by flakycov** [togglz/togglz#240]
`ZookeeperStateRepositoryTest::testZkNodeChangesUpdateFeatureState` fails for us on commit f033687e:

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.266 sec <<< FAILURE!
testZkNodeChangesUpdateFeatureState(org.togglz.zookeeper.ZookeeperStateRepositoryTest)  Time elapsed: 1.212 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <true>
     got: <false>

        at org.junit.Assert.assertThat(Assert.java:780)
        at org.junit.Assert.assertThat(Assert.java:738)
        at org.togglz.zookeeper.ZookeeperStateRepositoryTest.testZkNodeChangesUpdateFeatureState(ZookeeperStateRepositoryTest.java:155)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:228)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:134)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:113)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
```

We discovered this test to be flaky while using [DeFlaker](http://www.deflaker.org/).  Increasing the `Thread.sleep()` time in the test from 25 to about 200 reduces the rate of flakiness.

**Comment by chkal** [comment]
Thanks a lot for pointing this out. I increased the sleep duration to 500ms which should reduce it even more. Perhaps that's acceptable for now. Thank you very much.
