### ISSUE TITLE
Npe in QueryParameterActivationStrategy

### ISSUE THREAD

**Issue by CuervoSodieh** [togglz/togglz#260]
I am using version 2.5.0.Final of togglz

I am not sure how to reproduce it, but in some cases I get

```
Caused by: java.lang.NullPointerException
        at org.togglz.servlet.activation.QueryParameterActivationStrategy.getQueryParams(QueryParameterActivationStrategy.java:100) ~[togglz-servlet-2.5.0.Final.jar!/:?]
        at org.togglz.servlet.activation.QueryParameterActivationStrategy.getRefererParameters(QueryParameterActivationStrategy.java:78) ~[togglz-servlet-2.5.0.Final.jar!/:?]
        at org.togglz.servlet.activation.QueryParameterActivationStrategy.isActive(QueryParameterActivationStrategy.java:64) ~[togglz-servlet-2.5.0.Final.jar!/:?]
        at org.togglz.core.manager.DefaultFeatureManager.isActive(DefaultFeatureManager.java:86) ~[togglz-core-2.5.0.Final.jar!/:?]
```

**Comment by chkal** [comment]
Thank for reporting. I just pushed a fix for this issue. Could you give the latest snapshots a try? Have a look at [this page](https://www.togglz.org/download.html) for details.

**Comment by CuervoSodieh** [comment]
@chkal with the last snapshot it works, thanks for the fast help

**Comment by chkal** [comment]
Great! Thanks for testing!
