### ISSUE TITLE
java.lang.ClassNotFoundException: org.togglz.servlet.util.HttpServletRequestHolder

### ISSUE THREAD

**Issue by wgoldman1** [togglz/togglz#294]
2.6.0
I have the below (tried to also add togglz-servlet), did not help.

			
		<dependency>
			<groupId>org.togglz</groupId>
			<artifactId>togglz-core</artifactId>
			<version>${togglz.version}</version>
		</dependency>
		
			
		<dependency>
			<groupId>org.togglz</groupId>
			<artifactId>togglz-spring-core</artifactId>
			<version>${togglz.version}</version>
		</dependency>

		
		<dependency>
			<groupId>org.togglz</groupId>
			<artifactId>togglz-spring-web</artifactId>
			<version>${togglz.version}</version>
		</dependency>

        
        <dependency>
            <groupId>org.togglz</groupId>
            <artifactId>togglz-console</artifactId>
            <version>${togglz.version}</version>
        </dependency>

        
        
        <dependency>
            <groupId>org.togglz</groupId>
            <artifactId>togglz-jsp</artifactId>
            <version>${togglz.version}</version>
        </dependency>

        
        <dependency>
            <groupId>org.togglz</groupId>
            <artifactId>togglz-spring-security</artifactId>
            <version>${togglz.version}</version>
        </dependency>

**Comment by wgoldman1** [comment]
more of the stack
23-Jul-2018 11:01:13.339 SEVERE [http-nio-8080-exec-5] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [TogglzConsoleServlet] in context with path [/ClientPortal] threw exception [Servlet execution threw an exception] with root cause
 java.lang.ClassNotFoundException: org.togglz.servlet.util.HttpServletRequestHolder
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1305)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
	at org.togglz.spring.web.spi.SpringWebBeanFinder.getApplicationContext(SpringWebBeanFinder.java:24)
	at org.togglz.spring.spi.AbstractSpringBeanFinder.find(AbstractSpringBeanFinder.java:18)
	at org.togglz.core.context.BeanFinderFeatureManagerProvider.getFeatureManager(BeanFinderFeatureManagerProvider.java:38)
	at org.togglz.core.context.FeatureContext.findFeatureManagerInClassLoader(FeatureContext.java:108)
	at org.togglz.core.context.FeatureContext.getFeatureManagerOrNull(FeatureContext.java:74)
	at org.togglz.core.context.FeatureContext.getFeatureManager(FeatureContext.java:47)
	at org.togglz.core.manager.LazyResolvingFeatureManager.getDelegate(LazyResolvingFeatureManager.java:24)
	at org.togglz.core.manager.LazyResolvingFeatureManager.getCurrentFeatureUser(LazyResolvingFeatureManager.java:49)
	at org.togglz.console.TogglzConsoleServlet.isFeatureAdmin(TogglzConsoleServlet.java:75)
	at org.togglz.console.TogglzConsoleServlet.service(TogglzConsoleServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)

**Comment by ruifigueira** [comment]
Can you check if `togglz-servlet-*.jar` is included in your application which contains the `org.togglz.servlet.util.HttpServletRequestHolder` class? It should be transitively included by `togglz-spring-web`.

**Comment by wgoldman1** [comment]
so turns out I added togglz-servlet to my pom and it resolved the issue.

I previously simply added it to the pom and did a maven update for the project, then tried to find the class in eclipse, it did not show (I must have not been doing the maven update correctly, because now it does).

It is not transitively included, btw...
