### ISSUE TITLE
Parse Exception

### ISSUE THREAD

**Issue by epastoor** [togglz/togglz#536]
We use togglz in a non-spring boot application as a standalone servlet. We upgraded from 2.8.0 to 2.9.5 and now get this error when trying to access the page:

```
2021-03-11 16:32:51 SEVERE org.apache.catalina.core.StandardWrapperValve invoke Servlet.service() for servlet [TogglzConsoleServlet] in context with path [/apps] threw exception
org.togglz.console.shade.jmte.message.ParseException: Error while parsing 'param.value' at location (63:45): Property 'value' on object 'org.togglz.console.model.ParameterModel@4141032b' can not be accessed: "java.lang.reflect.InvocationTargetException"!
	at org.togglz.console.shade.jmte.message.DefaultErrorHandler.error(DefaultErrorHandler.java:18)
	at org.togglz.console.shade.jmte.DefaultModelAdaptor.nextStep(DefaultModelAdaptor.java:189)
	at org.togglz.console.shade.jmte.DefaultModelAdaptor.traverse(DefaultModelAdaptor.java:145)
	at org.togglz.console.shade.jmte.DefaultModelAdaptor.traverse(DefaultModelAdaptor.java:146)
	at org.togglz.console.shade.jmte.DefaultModelAdaptor.traverse(DefaultModelAdaptor.java:132)
	at org.togglz.console.shade.jmte.DefaultModelAdaptor.getValue(DefaultModelAdaptor.java:90)
	at org.togglz.console.shade.jmte.token.ExpressionToken.evaluatePlain(ExpressionToken.java:114)
	at org.togglz.console.shade.jmte.token.StringToken.evaluate(StringToken.java:77)
	at org.togglz.console.shade.jmte.template.InterpretedTemplate.content(InterpretedTemplate.java:281)
	at org.togglz.console.shade.jmte.template.InterpretedTemplate.condition(InterpretedTemplate.java:239)
	at org.togglz.console.shade.jmte.template.InterpretedTemplate.content(InterpretedTemplate.java:287)
	at org.togglz.console.shade.jmte.template.InterpretedTemplate.foreach(InterpretedTemplate.java:201)
	at org.togglz.console.shade.jmte.template.InterpretedTemplate.content(InterpretedTemplate.java:285)
	at org.togglz.console.shade.jmte.template.InterpretedTemplate.condition(InterpretedTemplate.java:239)
	at org.togglz.console.shade.jmte.template.InterpretedTemplate.content(InterpretedTemplate.java:287)
	at org.togglz.console.shade.jmte.template.InterpretedTemplate.foreach(InterpretedTemplate.java:201)
	at org.togglz.console.shade.jmte.template.InterpretedTemplate.content(InterpretedTemplate.java:285)
	at org.togglz.console.shade.jmte.template.InterpretedTemplate.foreach(InterpretedTemplate.java:201)
	at org.togglz.console.shade.jmte.template.InterpretedTemplate.content(InterpretedTemplate.java:285)
	at org.togglz.console.shade.jmte.template.InterpretedTemplate.transformPure(InterpretedTemplate.java:151)
	at org.togglz.console.shade.jmte.template.InterpretedTemplate.transform(InterpretedTemplate.java:140)
	at org.togglz.console.shade.jmte.Engine.transformInternal(Engine.java:194)
	at org.togglz.console.shade.jmte.Engine.transformInternal(Engine.java:185)
	at org.togglz.console.shade.jmte.Engine.transform(Engine.java:170)
	at org.togglz.console.handlers.index.IndexPageHandler.process(IndexPageHandler.java:62)
	at org.togglz.console.TogglzConsoleServlet.service(TogglzConsoleServlet.java:64)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:486)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by epastoor** [comment]
We were missing a new dependency.
